name: CI  # Название workflow

on: [push]  # Запускать workflow при каждом push в репозиторий

jobs:
  build:  # Название job
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      # Шаг 1: Получить код из репозитория
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Установить переменные окружения
      - name: Set up environment
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      # Шаг 3: Установить зависимости (например, для Node.js)
      - name: Install dependencies
        run: |
          npm install

      # Шаг 4: Запустить тесты
      - name: Run tests
        run: |
          npm test